### ISSUE TITLE
Lambda向けのCI/CDを検討する

### ISSUE THREAD

**Issue by m-namiki** [m-namiki/eim#9]
対象は `functions`以下のファイル群。ライブラリなどはどうするのが良いか調査する。

**Comment by m-namiki** [comment]
https://dev.classmethod.jp/articles/lambda-github-actions/

上記ページを参考に、`Github Actionsへのシークレット情報登録`まで実施した。

**Comment by m-namiki** [comment]
登録したRoleを他のGitHubActions実行時にも使いたいので、アタッチするポリシーとかを後から追加できるか調べる

**Comment by m-namiki** [comment]
`functions/`以下のファイルが更新された場合にワークフローが実行されるようにするための設定

例）`functions`以下のファイルが`develop`ブランチにpushされたとき
```yml
on:
  push:
    branches:
      - develop
  path:
    - "functions/**"
```
